spring:
  datasource:
    url: jdbc:postgresql://db:5432/logistica
    username: luis
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  app:
    jwt:
      secret: ${JWT_SECRET}