spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logistica
    username: luis
    password: 123456789

  sql:
    init:
      mode: never

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  cloud:
    aws:
      sqs:
        enabled: true
        endpoint: http://localhost:4566
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test

app:
  sqs:
    queue:
      ruta-cerrada: ruta-cerrada-queue
      contrato-creado: contrato-creado-queue
      novedad-estado-paquete: novedad-estado-paquete-queue

  servicios:
    conductores:
      base-url: https://6cfdb063-a734-47f4-911b-c0a53a6124c6.mock.pstmn.io
    banco:
      base-url: https://6cfdb063-a734-47f4-911b-c0a53a6124c6.mock.pstmn.io
      timeout-segundos: 10
      api-key: ${POSTMAN_API_KEY}