spring:
  datasource:
    url: jdbc:postgresql://db:5432/logistica
    username: luis
    password: 123456789
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    web-application-type: servlet

server:
  port: 8080
