spring:
  datasource:
    url: jdbc:postgresql://db:5432/logistica
    username: luis
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  cloud:
    aws:
      sqs:
        enabled: true
        endpoint: http://localstack:4566
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test

app:
  mock:
    tarifa:
      por-parada: 15000
      recorrido-completo: 80000
  sqs:
    queue:
      ruta-cerrada: ruta-cerrada-queue
      contrato-creado: contrato-creado-queue
      novedad-estado-paquete: novedad-estado-paquete-queue