spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logistica
    username: luis
    password: 123456789
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true