spring:
  datasource:
    url: jdbc:postgresql://db:5432/logistica
    username: luis
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

app:
  sqs:
    queue:
      ruta-cerrada: ruta-cerrada-queue
      contrato-creado: contrato-creado-queue
      novedad-estado-paquete: novedad-estado-paquete-queue