spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logistica_test
    username: luis
    password: 123456789
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

app:
  sqs:
    queue:
      ruta-cerrada: ruta-cerrada-queue
      contrato-creado: contrato-creado-queue